<template>
    <div class="modal" v-if="showModal">
      <div class="modal-content">
        <span class="close" @click="closeModal">&times;</span>
        <h2>Instructions</h2>
        <ol>
          <li>Click the button(CHATBOT).</li>
          <li>You will be directed to the openai playground.</li>
          <li>On the left corner, you will notice the System part. You can edit that to make the system behave to what you want it to be.
            <p><b>For example:</b> "You are a helpful assitant and an educated guidance counselor."</p>
          </li>
          <li>You can now type your message as a user and when you click the submit button, You will be having a response generated by OpenAI.</li>
          <li>Enjoy!</li>
        </ol>
      </div>
    </div>
  </template>
  
  <script>
  export default {
    props: {
      showModal: Boolean,
    },
    methods: {
      closeModal() {
        this.$emit("close");
      },
    },
  };
  </script>
  
  <style scoped>
  /* Add your modal styles here */
  .modal {
    display: block;
    position: fixed;
    z-index: 1;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgb(0, 0, 0);
    background-color: rgba(0, 0, 0, 0.4);
  }
  
  .modal-content {
    background-color: #fefefe;
    margin: 15% auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
  }
  
  .close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
  }
  
  .close:hover,
  .close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
  }
  </style>
  